### ISSUE TITLE
Can't authorize app

### ISSUE THREAD

**Issue by vistalba** [XanderStrike/goplaxt#3]
Plaxt docker runs into kubernetes with traefik as ingress controller. There is a valid Let's Encrypt Certificate for the plext URL.

If I open the web GUI,  type in my username and click "authorize" I can click the green button on trakt and come back to my URL but just with the "Bad gateway" message.
URL shows like this: 
```
https://plaxt.mydomain.com/authorize?username=plexusername&code=274a36081ea55442e478f0069aff301b003872e67d6b4d0a****************
```

The log output from the container looks like this:
```
2018/12/19 06:45:31 Started!
2018/12/19 06:45:57 Handling auth request for plexusername
2018/12/19 06:45:57 Got a 401 Unauthorized, full response:
&{401 Unauthorized 401 HTTP/2.0 2 0 map[Cache-Control:[no-store] X-Content-Type-Options:[nosniff] X-Request-Id:[ef589e09-ef1a-488d-b51b-6031045*****] Expect-Ct:[max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"] Content-Length:[213] X-Runtime:[0.005318] X-Xss-Protection:[1; mode=block] Date:[Wed, 19 Dec 2018 06:45:57 GMT] Pragma:[no-cache] Vary:[Accept-Encoding] Server:[cloudflare] Cf-Ray:[48b7e8ca2d8096b8-FRA] Content-Type:[application/json; charset=utf-8] Set-Cookie:[__cfduid=d0a10557c7757681cb531a5caa6c9471e1545******; expires=Thu, 19-Dec-19 06:45:57 GMT; path=/; domain=.trakt.tv; HttpOnly _traktsession=L2U3NU9uYTNFUFVPSkpjTnR1UVdjTVlqYUNoR2V0OGNmREFQckhNL3lPWnNDTE1XQ28xZHJzMzc1OVg4cGphcGRvcDc1SGNtRDJFb1BSUitlYWJzQnc9PS0tRmcrUFROb2MzMk5Fa21IL1VTN2I4dz09--47d916a3c67e5b6b279199c7fcf9fb5886******; path=/; HttpOnly] Cf-Railgun:[7798046614 1.87 0.012597 0030 57da] Www-Authenticate:[Bearer realm="Doorkeeper", error="invalid_grant", error_description="The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."] X-Frame-Options:[SAMEORIGIN]] {0xc4201e0280} 213 [] false false map[] 0xc420168500 0xc4200f6370}
2018/12/19 06:45:57 http: panic serving 10.32.0.1:43042: interface conversion: interface {} is nil, not string
goroutine 43 [running]:
net/http.(*conn).serve.func1(0xc420316d20)
        /usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x762460, 0xc42034e0c0)
        /usr/local/go/src/runtime/panic.go:502 +0x229
main.authorize(0x8108e0, 0xc420444000, 0xc420168300)
        /go/src/github.com/xanderstrike/goplaxt/main.go:33 +0x789
net/http.HandlerFunc.ServeHTTP(0x7e1350, 0x8108e0, 0xc420444000, 0xc420168300)
        /usr/local/go/src/net/http/server.go:1947 +0x44
github.com/xanderstrike/goplaxt/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4200d80c0, 0x8108e0, 0xc420444000, 0xc420168300)
        /go/src/github.com/xanderstrike/goplaxt/vendor/github.com/gorilla/mux/mux.go:215 +0xed
net/http.serverHandler.ServeHTTP(0xc42009b2b0, 0x8108e0, 0xc420444000, 0xc420168000)
        /usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420316d20, 0x810be0, 0xc42015c2c0)
        /usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2795 +0x27b
```

Any ideas what is wrong here?

------

Update: Please close this :) I'm sorry. Just have to put the /authorize out of the env. Sometimes it helps when I read the stuff again... Important: on trakt use "redirect uri with /authorize" in ENV var without!

**Comment by XanderStrike** [comment]
Glad you got it sorted!
