### ISSUE TITLE
[BUG] index out of range

### ISSUE THREAD

**Issue by HeavyDinosaur** [XanderStrike/goplaxt#50]
**Platform**: Docker

Running behind nginx proxy

I am able to successfully authorize a user, but when a video state change the application bugs out

```
2020/11/25 06:16:29 http: panic serving 192.168.68.139:54574: runtime error: index out of range
goroutine 94 [running]:
net/http.(*conn).serve.func1(0xc0004b7180)
        /usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x85f6c0, 0xcc4cc0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/xanderstrike/goplaxt/lib/trakt.findEpisode(0xc0005ec220, 0xb, 0x101, 0x1, 0xc0005b2800, 0x3a, 0xc0005ec1f8, 0x8, 0xc0005ec248, 0x4, ...)
        /go/src/github.com/xanderstrike/goplaxt/lib/trakt/main.go:85 +0x755
github.com/xanderstrike/goplaxt/lib/trakt.HandleShow(0xc0005ec220, 0xb, 0x101, 0x1, 0xc0005b2800, 0x3a, 0xc0005ec1f8, 0x8, 0xc0005ec248, 0x4, ...)
        /go/src/github.com/xanderstrike/goplaxt/lib/trakt/main.go:59 +0xde
github.com/xanderstrike/goplaxt/lib/trakt.Handle(0xc0005ec220, 0xb, 0x101, 0x1, 0xc0005b2800, 0x3a, 0xc0005ec1f8, 0x8, 0xc0005ec248, 0x4, ...)
        /go/src/github.com/xanderstrike/goplaxt/lib/trakt/main.go:47 +0x14f
main.api(0x984960, 0xc0005dc000, 0xc0000ee700)
        /go/src/github.com/xanderstrike/goplaxt/main.go:104 +0x759
net/http.HandlerFunc.ServeHTTP(0x900a58, 0x984960, 0xc0005dc000, 0xc0000ee700)
        /usr/local/go/src/net/http/server.go:1995 +0x44
main.allowedHostsHandler.func1.1(0x984960, 0xc0005dc000, 0xc0000ee700)
        /go/src/github.com/xanderstrike/goplaxt/main.go:135 +0x2f3
net/http.HandlerFunc.ServeHTTP(0xc00007d4a0, 0x984960, 0xc0005dc000, 0xc0000ee700)
        /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/handlers.ProxyHeaders.func1(0x984960, 0xc0005dc000, 0xc0000ee700)
        /go/pkg/mod/github.com/gorilla/handlers@v1.5.1/proxy_headers.go:59 +0x10d
net/http.HandlerFunc.ServeHTTP(0xc0005a8020, 0x984960, 0xc0005dc000, 0xc0000ee700)
        /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000aa0c0, 0x984960, 0xc0005dc000, 0xc0000ee400)
        /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xe3
net/http.serverHandler.ServeHTTP(0xc000084a90, 0x984960, 0xc0005dc000, 0xc0000ee400)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0004b7180, 0x9854a0, 0xc00005a100)
        /usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4
```

**Comment by XanderStrike** [comment]
I think this was related to [a bug in Plex's webooks](https://forums.plex.tv/t/bug-webhooks-returning-multiple-guid-fields-of-different-datatypes/636921) that they're refusing to fix. Are you still seeing the error?

**Comment by HeavyDinosaur** [comment]
I just run the program and it is now working
